// Electron main process of the opt-in TLS probe (tests/tls-probe/run-tls-probe.mjs
// launches it; it is NOT part of `npm test` or `npm run smoke`).
//
// It builds the app's REAL controller TLS sessions (ControllerTlsSessions from
// dist/main/cert-verify.js, which installs the verify proc that applies
// dist/main/cert-pinning.js on every in-memory partition it creates), then
// drives Electron's net.request() — the module the app's API client uses, with
// the same `session` option as src/main/net-transport.ts — against local HTTPS
// servers on 127.0.0.1 that present self-signed certificates generated by the
// runner with the openssl CLI. Each step prints one `PROBE <json>` line; the
// runner turns them into PASS/FAIL checks.
//
// Isolation (invariant D4): only 127.0.0.1 is contacted; the script refuses to
// start unless HOME points away from the real home directory, and keeps
// Electron's userData inside that temp HOME. Nothing reads or writes
// ~/.omada-wlan-manager/.

'use strict';

const { app, net, session } = require('electron');
const fs = require('node:fs');
const https = require('node:https');
const os = require('node:os');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..', '..');
const { ControllerTlsSessions, installCertificateVerifyProc } = require(path.join(projectRoot, 'dist', 'main', 'cert-verify.js'));

const REQUEST_TIMEOUT_MS = 10000;

// ============================================================================
// D4 guard and environment
// ============================================================================

if (path.resolve(os.homedir()) === path.resolve(os.userInfo().homedir)) {
  console.error('[tls-probe] Refusing to start: HOME must point at a fresh temp directory');
  process.exit(2);
}
app.setPath('userData', path.join(os.homedir(), 'electron-user-data'));

const certDir = process.env.OMADA_TLS_PROBE_CERTS;
if (!certDir || !fs.existsSync(certDir)) {
  console.error('[tls-probe] OMADA_TLS_PROBE_CERTS must point at the runner\'s certificate directory');
  process.exit(2);
}

/**
 * Reads one generated key pair.
 * @param {string} name - Certificate name ('A' or 'B').
 * @returns {{ key: Buffer; cert: Buffer }} The PEM key and certificate.
 */
function readPair(name) {
  return {
    key: fs.readFileSync(path.join(certDir, `key${name}.pem`)),
    cert: fs.readFileSync(path.join(certDir, `cert${name}.pem`)),
  };
}

const PAIRS = { A: readPair('A'), B: readPair('B') };

// ============================================================================
// Trust source (the app's is backed by the config cache; this one by memory)
// ============================================================================

const trust = {
  configuredUrl: '',
  pin: null,
  rejections: [],
};

const source = {
  /** @returns {string} The configured controller URL. */
  getConfiguredUrl: () => trust.configuredUrl,
  /** @returns {object | null} The stored pin. */
  getCertificatePin: () => trust.pin,
  /**
   * Records a first-use / mismatch rejection (the app's OMADA_CONNECT reads it).
   * @param {object} rejection - The rejection.
   */
  onPinRejection: (rejection) => {
    trust.rejections.push(rejection);
  },
};

// ============================================================================
// Local HTTPS servers
// ============================================================================

/**
 * Starts an HTTPS server on 127.0.0.1 presenting the given certificate. It
 * counts TLS connections and HTTP requests, so a step can prove that a
 * rejected handshake never delivered an HTTP request (no credential could
 * have been sent).
 * @param {'A' | 'B'} certName - Which generated certificate to present.
 * @param {number} [port] - Port to bind (0 = any free port).
 * @returns {Promise<{ port: number; certName: string; stats: { tls: number; requests: number }; close: () => Promise<void> }>}
 */
function startServer(certName, port = 0) {
  const stats = { tls: 0, requests: 0 };
  const server = https.createServer({ ...PAIRS[certName] }, (request, response) => {
    stats.requests++;
    response.writeHead(200, { 'Content-Type': 'application/json' });
    response.end(JSON.stringify({ errorCode: 0, msg: 'probe', result: { omadacId: 'probe' } }));
  });
  server.keepAliveTimeout = 60000;
  server.on('secureConnection', () => {
    stats.tls++;
  });
  server.on('tlsClientError', () => {
    // A client aborting the handshake (the verify proc rejected) is expected
  });
  return new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(port, '127.0.0.1', () => {
      resolve({
        port: server.address().port,
        certName,
        stats,
        /**
         * Closes the server and every open connection.
         * @returns {Promise<void>}
         */
        close: () => new Promise((done) => {
          server.closeAllConnections();
          server.close(() => done());
        }),
      });
    });
  }); // End of the listen promise
} // End of function startServer()

// ============================================================================
// Requests (Electron's net module, like src/main/net-transport.ts)
// ============================================================================

/**
 * Sends one GET with net.request() on the given session and reports how it ended.
 * @param {Electron.Session} requestSession - Session to send the request on.
 * @param {string} url - URL to request.
 * @returns {Promise<{ ok: boolean; status: number | null; error: string | null }>}
 */
function netGet(requestSession, url) {
  return new Promise((resolve) => {
    let settled = false;
    /**
     * Resolves exactly once.
     * @param {{ ok: boolean; status: number | null; error: string | null }} value - Outcome.
     */
    const finish = (value) => {
      if (!settled) {
        settled = true;
        clearTimeout(timer);
        resolve(value);
      }
    };
    const request = net.request({ method: 'GET', url, session: requestSession });
    const timer = setTimeout(() => {
      request.abort();
      finish({ ok: false, status: null, error: 'timeout' });
    }, REQUEST_TIMEOUT_MS);
    request.on('response', (response) => {
      response.on('data', () => {});
      response.on('end', () => finish({ ok: response.statusCode === 200, status: response.statusCode, error: null }));
      response.on('error', (error) => finish({ ok: false, status: response.statusCode, error: error.message }));
    });
    request.on('error', (error) => finish({ ok: false, status: null, error: error.message }));
    request.end();
  }); // End of the request promise
} // End of function netGet()

/**
 * Runs one request on the CURRENT controller session and measures what it
 * caused: the outcome, the rejections the verify proc reported meanwhile, and
 * the server's TLS/HTTP counters.
 * @param {ControllerTlsSessions} tls - The controller sessions.
 * @param {{ port: number; stats: { tls: number; requests: number } }} server - Target server.
 * @returns {Promise<object>} Outcome plus deltas.
 */
async function measuredGet(tls, server) {
  const before = { rejections: trust.rejections.length, tls: server.stats.tls, requests: server.stats.requests };
  const outcome = await netGet(tls.session, `https://127.0.0.1:${server.port}/api/info`);
  // Let the server-side counters settle (the request event may trail the response)
  await new Promise((resolve) => setTimeout(resolve, 50));
  return {
    ...outcome,
    newRejections: trust.rejections.slice(before.rejections),
    serverTlsConnections: server.stats.tls - before.tls,
    serverHttpRequests: server.stats.requests - before.requests,
  };
} // End of function measuredGet()

/**
 * Prints one step result for the runner.
 * @param {string} step - Step id.
 * @param {object} data - Step data.
 */
function report(step, data) {
  process.stdout.write(`PROBE ${JSON.stringify({ step, ...data })}\n`);
}

// ============================================================================
// The scenario
// ============================================================================

/**
 * Runs steps (a)–(d) plus the informational control steps that show what
 * happens WITHOUT a controller-session reset (the reason the app resets it),
 * and that closing connections + re-installing the proc is not enough.
 * @returns {Promise<void>}
 */
async function runProbe() {
  // Same construction as src/main/index.ts (only the partition prefix differs)
  const tls = new ControllerTlsSessions((partition) => session.fromPartition(partition), source, 'omada-tls-probe');

  // Controller "A": self-signed certificate A on port P1
  let serverP1 = await startServer('A');
  const port1 = serverP1.port;
  trust.configuredUrl = `https://127.0.0.1:${port1}`;
  const origin = trust.configuredUrl;
  report('setup', { origin, electron: process.versions.electron, chrome: process.versions.chrome });

  // (a) First use: no pin -> rejected during the handshake; no HTTP request
  const firstUse = await measuredGet(tls, serverP1);
  report('a-first-use', firstUse);

  // Controls: an immediate repeat with no reset, and one after closing all
  // connections + re-installing the verify proc on the SAME session — does
  // Chromium ask the verify proc again or answer from its verdict cache?
  report('a-control-repeat-without-reset', await measuredGet(tls, serverP1));
  await tls.session.closeAllConnections();
  installCertificateVerifyProc(tls.session, source);
  report('a-control-close-connections-and-reinstall-proc', await measuredGet(tls, serverP1));

  // (a') The app resets the controller session before a connect that follows
  // a pin rejection: the repeat must run the verify proc again
  await tls.reset();
  report('a-repeat-after-reset', await measuredGet(tls, serverP1));

  // (b) Trust: store the fingerprint the verify proc recorded
  const recorded = firstUse.newRejections[0];
  trust.pin = { origin, sha256: recorded ? recorded.fingerprint : '', trustedAt: new Date().toISOString() };
  // Control: retry without a reset (a cached rejection would fail it)
  report('b-control-retry-without-reset', await measuredGet(tls, serverP1));
  // What CERT_TRUST does, then the immediate retry
  await tls.reset();
  report('b-retry-after-trust', await measuredGet(tls, serverP1));

  // (c) The server switches to a different self-signed certificate B on the
  // same port (all old connections dropped, as with a real swap)...
  await serverP1.close();
  serverP1 = await startServer('B', port1);
  report('c-mismatch-same-port', await measuredGet(tls, serverP1));
  // ...and certificate B on a DIFFERENT port of the same host, in a fresh
  // session so the verify proc must decide again (the verify proc sees only
  // the hostname, so the pin is what rejects it)
  const serverP2 = await startServer('B');
  await tls.reset();
  report('c-mismatch-other-port', { port: serverP2.port, ...(await measuredGet(tls, serverP2)) });
  // Informational: the pinned certificate A on another port is the same
  // identity (same key) and is accepted
  const serverP3 = await startServer('A');
  report('c-info-pinned-cert-other-port', { port: serverP3.port, ...(await measuredGet(tls, serverP3)) });

  // (d) Reset. First restore certificate A on P1 and make one accepted
  // request, so a pooled keep-alive connection and a cached acceptance exist
  await serverP1.close();
  serverP1 = await startServer('A', port1);
  report('d-before-reset-accepted', await measuredGet(tls, serverP1));
  trust.pin = null;
  // Control: the pin is gone but the session was not reset (stale acceptance?)
  report('d-control-without-reset', await measuredGet(tls, serverP1));
  // What CERT_RESET does, then the next connection
  await tls.reset();
  report('d-after-reset', await measuredGet(tls, serverP1));

  await Promise.all([serverP1.close(), serverP2.close(), serverP3.close()]);
} // End of function runProbe()

app.whenReady().then(async () => {
  try {
    await runProbe();
    process.stdout.write('PROBE_DONE\n');
  } catch (error) {
    console.error('[tls-probe] failed:', error);
    process.exitCode = 1;
  } finally {
    app.quit();
  }
}); // End of the app ready handler

app.on('window-all-closed', () => {
  // No windows are ever created; keep the default quit behavior explicit
});
